export enum Variants {
  Primary = 'primary',
  Secondary = 'secondary',
  Success = 'success',
  Danger = 'danger',
  Warning = 'warning',
  Info = 'info',
  Light = 'light',
  Dark = 'dark',
  OutlinedPrimary = 'outline-primary',
  OutlinedSecondary = 'outline-secondary',
  OutlinedSuccess = 'outline-success',
  OutlinedDanger = 'outline-danger',
  OutlinedWarning = 'outline-warning',
  OutlinedInfo = 'outline-info',
  OutlinedLight = 'outline-light',
  OutlinedDark = 'outline-dark',
}
